version: '3'

services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile
        ports:
            - "8080:8080"
        environment:
            - "SERVER_PORT=8080"
            - "POSTGRES_HOST=db"
        env_file:
            -   apps/api/.env
        depends_on:
            -   db
        restart: on-failure
        networks:
            - default
            - backend
            - database

    db:
        build:
            context: .
            dockerfile: postgres.dockerfile
        ports:
            - "5432:5432"
        volumes:
            - ./apps/api/db/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        restart: on-failure
        networks:
            - default
            - backend
            - database

    front:
        build:
            context: .
            dockerfile: front.dockerfile
        ports:
            - "3000:3000"
        restart: on-failure
        depends_on:
            - api
        networks:
            - default
            - backend

networks:
    default:
        external: false
    backend:
        external: false
    database:
        external: false
