version: '3'

services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile
        ports:
            - "8080:8080"
        environment:
            - "SERVER_PORT=8080"
            - "POSTGRES_HOST=db"
        env_file:
            -   apps/api/.env
    db:
        build:
            context: apps/api
            dockerfile: Dockerfile.postgres
        ports:
            - "5432:5432"
        volumes:
            - ./apps/api/db/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        restart: always

    front:
        build:
            context: apps/front
            dockerfile: Dockerfile.front
        ports:
            - "3000:3000"
        depends_on:
            - db
        restart: always
