name: Builder
on: [pull_request]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/${{matrix.directory}}/node_modules
          key: modules-${{ hashFiles(format('{0}/package-lock.json', matrix.directory)) }}
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - run: npm i
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./${{matrix.directory}}
        name: Install dependencies
  build-app:
    name: Build
    needs: install-dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms: [ "ios", "android" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./app/node_modules
          key: modules-${{hashFiles(format('{0}/package-lock.json', 'app'))}}
      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
            expo-version: 4.x
            expo-token: ${{ secrets.EXPO_TOKEN }}
            expo-cache: true
      - name: Build ${{matrix.platforms}} on EAS
        working-directory: ./app
        run: npx eas-cli build --platform ${{matrix.platforms}} --non-interactive
      - name: Upload Artifcat
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: app-${{matrix.platforms}}
          path: ./app/dist
  build-front:
    name: Build Front
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./front/node_modules
          key: modules-${{hashFiles(format('{0}/package-lock.json', 'front'))}}
      - run: npm run build
        working-directory: ./front
        name: Build front
      - name: Upload Artifcat
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: front
          path: ./front/dist
  build-api:
    name: Build API
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./api/node_modules
          key: modules-${{hashFiles(format('{0}/package-lock.json', 'api'))}}
      - run: npm run build
        working-directory: ./api
        name: Build api
      - name: Upload Artifcat
        id: upload
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: ./api/dist
