name: Linter
on: [ push, workflow_dispatch ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - run: npm i
        if: steps.cache.outputs.cache-hit != 'true'
        name: Install dependencies
  lint:
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
      fail-fast: false
    name: Lint
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run lint
        working-directory: ./apps/${{matrix.directory}}
        name: Lint
  prettier:
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
    name: Prettier
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run prettier
        working-directory: ./apps/${{matrix.directory}}
        name: Prettier
  openapi:
    needs: install-dependencies
    name: Validate OpenAPI Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
              ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run validate-swagger
        working-directory: ./apps/api
        name: Validate OpenAPI Schema
  check-types:
    strategy:
      matrix:
        directory: [ "app", "api", "front" ]
    name: Validate TypeScript
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ./apps/api/node_modules
            ./apps/app/node_modules
            ./apps/front/node_modules
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm run check-types
        working-directory: ./apps/${{matrix.directory}}
        name: Checking TypeScript
