name: Build CI
on:
  pull_request:
    branches:
      - 'master'

jobs:
  install-dependencies:
    name: Install dependencies
    uses: vanerac/dashboard-v2/.github/workflows/install-dependencies.yml@master
  lint:
    name: Lint
    needs: install-dependencies
    uses: vanerac/dashboard-v2/.github/workflows/lint.yml@master
  prettier:
    name: Prettier
    needs: install-dependencies
    uses: vanerac/dashboard-v2/.github/workflows/prettier.yml@master
  openapi:
    name: Verify OpenAPI Definition
    needs: install-dependencies
    uses: vanerac/dashboard-v2/.github/workflows/validate-swagger.yml@master
  check-types:
    name: Verify Compilation
    needs: install-dependencies
    uses: vanerac/dashboard-v2/.github/workflows/compile-ts.yml@master
  build-app:
    name: Build App
    needs: [lint, prettier, openapi, check-types]
    uses: vanerac/dashboard-v2/.github/workflows/build-app.yml@master
  build-front:
    name: Build Front
    needs: [lint, prettier, openapi, check-types]
    uses: vanerac/dashboard-v2/.github/workflows/build-front.yml@master
  build-api:
    name: Build API
    needs: [lint, prettier, openapi, check-types]
    uses: vanerac/dashboard-v2/.github/workflows/build-api.yml@master
