on: [ push ]
name: Repository Sync

jobs:
  link:
    name: link
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add remote
        run: |
          git remote add upstream https://${{secrets.TOKEN_GITHUB}}@github.com/EpitechPromo2024/B-YEP-500-BDX-5-1-area-corentin.mas.git
      - name: Push upstream
        run: |
          git fetch upstream
      - name: Push
        run: |
          git push upstream
